DROP TABLE IF EXISTS Pilot_Plane;
DROP TABLE IF EXISTS Pilot;
DROP TABLE IF EXISTS Plane;
DROP TABLE IF EXISTS Operator;
DROP TABLE IF EXISTS Hub;
DROP TABLE IF EXISTS Producer;
DROP TABLE IF EXISTS Hangar;
